Bla-bla orginize your code to focus more on experiments, not bugs.

My way.

In [12]:
from IPython.display import display

Про match_id вместо MatchId и Python-style

In [1]:
from utils import load_data

df = load_data('train', 'input', nrows=10000)
df.head()

,id,group_id,match_id,assists,boosts,damage_dealt,dbn_os,headshot_kills,heals,kill_place,...,revives,ride_distance,road_kills,swim_distance,team_kills,vehicle_destroys,walk_distance,weapons_acquired,win_points,win_place_perc
0,7f96b2f878858a,4d4b580de459be,a10357fd1a4a91,0,0,0.00,0,0,0,60,...,0,0.0000,0,0.00,0,0,244.80,1,1466,0.4444
1,eef90569b9d03c,684d5656442f9e,aeb375fc57110c,0,0,91.47,0,0,0,57,...,0,0.0045,0,11.04,0,0,1434.00,5,0,0.6400
2,1eaf90ac73de72,6a4a42c3245a74,110163d8bb94ae,1,0,68.00,0,0,0,47,...,0,0.0000,0,0.00,0,0,161.80,2,0,0.7755
3,4616d365dd2853,a930a9c79cd721,f1f1f4ef412d7e,0,0,32.90,0,0,0,75,...,0,0.0000,0,0.00,0,0,202.70,3,0,0.1667
4,315c96c26c9aac,de04010b3458dd,6dc8ff871e21e6,0,0,100.00,0,0,0,45,...,0,0.0000,0,0.00,0,0,49.75,2,0,0.1875

Про удобство селекции колонок

In [19]:
from utils import split_columns_by_types

columns = split_columns_by_types(df)
display(df[columns['id']].head(), df[columns['target']].head())

               id        group_id        match_id
0  7f96b2f878858a  4d4b580de459be  a10357fd1a4a91
1  eef90569b9d03c  684d5656442f9e  aeb375fc57110c
2  1eaf90ac73de72  6a4a42c3245a74  110163d8bb94ae
3  4616d365dd2853  a930a9c79cd721  f1f1f4ef412d7e
4  315c96c26c9aac  de04010b3458dd  6dc8ff871e21e6

0    0.4444
1    0.6400
2    0.7755
3    0.1667
4    0.1875
Name: win_place_perc, dtype: float64